# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nashafa's Blog
email: contact@nashafa.com
description: >
  Just a boy and his keyboard
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.nashafa.com" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

name: 'Nathan Fallahi'
bio: >
  Current high school student in Newport Beach. Welcome to my world.
author_image: "/assets/images/author.jpg"
twitter_username: Nashafa
github_username:  Nashafa

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

gems: [jekyll-paginate]
